// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fibonacci
int fibonacci(const int x);
RcppExport SEXP fib_fibonacci(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type x(xSEXP);
    __result = Rcpp::wrap(fibonacci(x));
    return __result;
END_RCPP
}
// countsum
double countsum(const int x);
RcppExport SEXP fib_countsum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type x(xSEXP);
    __result = Rcpp::wrap(countsum(x));
    return __result;
END_RCPP
}
